services:
  ollama:
    build:
      context: qwen3.5-9b/.
    container_name: ollama
    ports:
      - "11434:11434"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]